# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    #    # valid drivers options include "gd" or "gmagick" or "imagick"
    #    driver: "gd"
    #
    #    # define your filter sets under this option
    filter_sets:
        #
        #        # an example thumbnail transformation definition
        #        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [200, 200]
                    mode:          outbound
                    allow_upscale: true

        rectangled_thumbnail_mini:
            filters:
                thumbnail:
                    size:          [90, 60]
                    mode:          outbound
                    allow_upscale: true

        rectangled_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [450, 300]
                    mode:          outbound
                    allow_upscale: true

        rectangled_thumbnail_big:
            filters:
                thumbnail:
                    size:          [600, 2400]
                    mode:          outbound
                    allow_upscale: true

        my_ratio_up_scale_filter:
            filters:
                scale:
                    to: 2
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail: